In [1]:
import numpy as np
import pandas as pd
import xgboost
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import StratifiedKFold

In [2]:
stack_1 = pd.read_pickle('stack/stack_1.pkl')[0].values
stack_2 = pd.read_pickle('stack/stack_2.pkl')[0].values
stack_3 = pd.read_pickle('stack/stack_3.pkl')[0].values

In [3]:
stack = []
for i in range(stack_1.shape[0]):
    s1, s2, s3 = stack_1[i], stack_2[i], stack_3[i]
    if s1 != -1: stack.append(s1)
    if s2 != -1: stack.append(s2)
    if s3 != -1: stack.append(s3)

In [4]:
stack_arr = np.array(stack)

In [5]:
result_1 = pd.read_pickle('stack/result_1.pkl')['category'].values
result_2 = pd.read_pickle('stack/result_2.pkl')['category'].values
result_3 = pd.read_pickle('stack/result_3.pkl')['category'].values

In [6]:
result = []
for i in range(result_1.shape[0]):
    sum = result_1[i] + result_2[i] + result_3[i]
    if sum > 1: result.append(1)
    else: result.append(0)
result_arr = np.array(result)

In [50]:
data_set = np.loadtxt("dataset/training_set.txt").astype(np.int64)
data = data_set[:, :2]
y = data_set[:, -1]

In [196]:
classic = pd.read_pickle('features.pkl')

In [197]:
classic = classic[['year1', 'year2',
                    # 'year_differ',
                     #'sameAutCount',
                     #'sameTitleWord',
                     #'sameT1Ab2',
                     #'sameT2Ab1',
                    # 'sameAbstract',
                     'T1T2_c',
                     'T1Ab2_c',
                     'T2Ab1_c',
                     'Ab1Ab2_c',
                     'aut1_sum', 'aut2_sum',#'aut_sum',
                     'connection1', 'connection2',
                     #'connection_max',
                     'len1', 'len2',
                    # 'j1', 'j2',
                    # 'year_sum',
                    # 'wmDistance'
                   'edge2',
                   'edge3',
                   'edge2_neg',
                   'edge3_neg',
                   'edge3_neg_middle',
                   'edge3_neg_sid',
                 #  'edge4'
                  # 'path',
                  # 'double_connex1',
                  # 'double_connex2',
                  # 'nocom_connex1',
                  # 'nocom_connex2',
                   'edge2_weighted',
                  # 'sameAut',
                  # 'AAA_edge',
                  #  'ADA_edge',
                  # '=A=D=A=',
                   'edge3_weighted',
                   #'sameJ',
                   #'edge2_123_weighted',
                   #'edge2_sqr_weighted',
                   #'connex_max','connex_min',
                   #'year_max','year_min',
                   '->D->',#'->D<-','<-D->',
                   #'->D->_w',
                   #'->D->D->',
                   #'src1','tgt2',
                    ]]

In [616]:
classic['edge23'] = list(map(lambda x: 50*x[0] + x[1], zip(classic['edge2'].values.tolist(), classic['edge3'].values.tolist())))

In [198]:
classic['rnn'] = stack_arr

In [199]:
lsa1 = pd.read_pickle('lsa1.pkl')
lsa2 = pd.read_pickle('lsa2.pkl')
#X = np.concatenate((classic.values, lsa1.values[:,:15], lsa2.values[:,:15]), axis=1)

In [200]:
d2v1 = pd.read_pickle('d2v1.pkl')
d2v2 = pd.read_pickle('d2v2.pkl')
X = np.concatenate((classic.values, lsa1.values[:,:15], lsa2.values[:,:15], d2v1.values[:,:0], d2v2.values[:,:0]), axis=1)

In [201]:
seed = 7
test_size = 0.15
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=seed)

In [202]:
X_train.shape

(523185, 52)

In [203]:
model = XGBClassifier(max_depth=12, n_jobs = 4, objective='binary:logistic')
model.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=12, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=4, nthread=None, objective='binary:logistic', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [507]:
model.save_model('xgb.model')

In [466]:
fscore = model.feature_importances_

In [467]:
fscore

array([0.08367735, 0.08143529, 0.01347023, 0.04013488, 0.03817752,
       0.0853767 , 0.09057262, 0.09299263, 0.11257518, 0.10231681,
       0.1303872 , 0.12506673, 0.00381686], dtype=float32)

In [206]:
y_pred = model.predict(X_test)
predictions = [round(value) for value in y_pred]

D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

In [207]:
accuracy = accuracy_score(y_test, predictions)
print("Accuracy: %.3f%%" % (accuracy * 100.0))

Accuracy: 97.878%

In [179]:
features_test = pd.read_pickle('features_test.pkl')

In [180]:
features_test = features_test[['year1', 'year2',
                     #'year_differ',
                     #'sameAutCount',
                     #'sameTitleWord',
                     #'sameT1Ab2',
                     #'sameT2Ab1',
                    # 'sameAbstract',
                     'T1T2_c',
                     'T1Ab2_c',
                     'T2Ab1_c',
                     'Ab1Ab2_c',
                     'aut1_sum', 'aut2_sum',#'aut_sum',
                     'connection1', 'connection2',
                     #'connection_max',
                     'len1', 'len2',
                    # 'j1', 'j2',
                    # 'year_sum',
                    # 'wmDistance'
                   'edge2',
                   'edge3',
                   'edge2_neg',
                   'edge3_neg',
                   'edge3_neg_middle',
                   'edge3_neg_sid',
                  # 'edge4'
                   # 'path',
                  # 'double_connex1',
                   #'double_connex2',
                    'edge2_weighted',
                   # 'sameAut',
                    #'ADA_edge',
                    #'=A=D=A=',
                    'edge3_weighted'
                    ]]

In [606]:
features_test['edge23'] = list(map(lambda x: 50*x[0] + x[1], zip(features_test['edge2'].values.tolist(), features_test['edge3'].values.tolist())))

In [181]:
features_test['rnn'] = result_arr

In [182]:
lsa_test1 = pd.read_pickle('lsa_test1.pkl')
lsa_test2 = pd.read_pickle('lsa_test2.pkl')
X = np.concatenate((features_test.values, lsa_test1.values[:,:15], lsa_test2.values[:,:15]), axis=1)

In [183]:
y_pred = model.predict(X)
predictions = [round(value) for value in y_pred]

D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

In [184]:
pred_dict = {idx: predictions[idx] for idx in range(len(predictions))}
submission = pd.DataFrame.from_dict(pred_dict,orient='index')
submission.index.names = ['id']
submission.columns = ['category']
submission.to_csv("submission.csv")

In [156]:
features_test

NameError: name 'features_test' is not defined

In [184]:
X.shape

(32648, 52)

In [168]:
classic

,year1,year2,T1T2_c,T1Ab2_c,T2Ab1_c,Ab1Ab2_c,aut1_sum,aut2_sum,connection1,connection2,...,len2,edge2,edge3,edge2_neg,edge3_neg,edge3_neg_middle,edge3_neg_sid,edge2_weighted,edge3_weighted,rnn
0,1995,1995,2,3,4,7,-1,1120,5,11,...,79,1,0,0,0,0,0,7,0,1
1,1997,1996,1,1,1,8,2,29,78,146,...,53,20,1417,0,12,4,8,3097,47979053,1
2,1993,1995,0,3,1,9,0,3,1,5,...,290,0,0,0,0,0,0,0,0,0
3,1999,2003,0,2,1,14,1127,39,20,14,...,92,0,24,0,3,0,3,0,1403996,0
4,1997,2002,0,1,1,12,-1,4,7,24,...,81,0,1,0,0,0,0,0,5915,0
5,1997,1997,0,15,4,52,-1,3,37,34,...,135,14,328,0,4,1,3,2142,8071583,1
6,1999,1995,0,0,4,13,-1,-1,60,738,...,81,12,1483,1,57,34,23,3245,114690192,1
7,2002,1995,1,3,5,15,-1,25,15,86,...,100,0,0,0,3,1,2,0,0,0
8,1997,1997,0,1,0,5,4,73,40,99,...,92,5,433,0,7,1,6,1829,41775069,1
9,2000,1992,0,1,0,5,26,67,4,30,...,43,0,0,0,0,0,0,0,0,0
10,1994,2001,0,0,0,1,13,-1,3,21,...,83,0,0,0,3,0,3,0,0,0
11,1997,1997,0,1,0,8,20,12,19,6,...,75,0,18,0,0,0,0,0,97433,0
12,2001,2000,0,0,0,3,2,40,14,40,...,122,0,0,0,5,0,5,0,0,0
13,2001,1993,1,5,0,6,1,1,28,10,...,131,0,3,0,8,0,8,0,40610,0
14,1998,1992,0,2,0,9,0,53,5,2,...,68,0,0,0,0,0,0,0,0,0
15,1994,1995,0,0,3,22,36,0,15,3,...,277,0,0,0,1,0,1,0,0,0
16,2000,2002,0,0,0,10,0,43,3,74,...,119,0,6,0,7,0,7,0,572753,0
17,2002,1998,0,5,1,19,53,60,23,98,...,57,5,183,0,7,2,5,2480,21516286,1
18,1995,1993,0,0,0,5,60,5,75,41,...,53,10,248,0,4,3,1,355,657580,1
19,1993,1995,0,0,0,4,2,4,10,20,...,88,0,0,0,0,0,0,0,0,0
20,1996,1999,0,0,0,2,4,1123,16,14,...,144,0,0,0,0,0,0,0,0,0
21,2000,2001,0,0,0,14,18,114,17,50,...,133,0,16,0,4,0,4,0,580149,0
22,2001,1997,0,1,2,23,46,10,83,2345,...,182,40,5641,0,193,154,39,5927,289415796,1
23,1994,1999,0,2,0,13,-1,31,104,31,...,34,2,93,0,8,2,6,161,7765426,1
24,1995,1992,1,1,9,38,34,46,22,13,...,136,3,61,0,2,1,1,94,94563,1
25,1997,1998,0,2,2,12,-1,31,4,1,...,98,0,0,0,0,0,0,0,0,0
26,2000,2000,0,0,0,2,7,30,9,40,...,53,0,0,0,3,1,2,0,0,0
27,1997,2001,0,0,0,1,11,9,7,26,...,191,0,0,0,0,0,0,0,0,0
28,1997,1995,0,7,0,15,-1,-1,90,1108,...,122,17,3950,0,122,62,60,6465,212896530,1
29,2001,2001,0,0,0,2,63,27,34,95,...,80,0,15,1,19,0,19,0,1570586,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615482,1994,2002,0,0,3,23,-1,0,18,33,...,203,0,0,0,10,1,9,0,0,0
615483,1995,1994,2,6,2,18,1106,6,18,13,...,88,11,62,0,0,0,0,194,27548,1
615484,1999,1997,0,1,9,42,1135,57,150,46,...,118,9,285,0,33,3,30,708,7988230,1
615485,1993,1999,1,3,2,6,3,21,8,53,...,51,0,0,0,0,0,0,0,0,0
615486,2000,2001,0,0,0,7,7,1109,12,2,...,97,0,0,0,0,0,0,0,0,0
615487,1999,1999,0,0,0,9,59,11,74,4,...,150,0,0,0,3,0,3,0,0,0
615488,2000,1994,0,0,0,0,17,1,15,13,...,92,0,0,0,2,0,2,0,0,0
615489,2002,1998,0,0,0,5,8,0,21,3,...,95,0,0,0,1,0,1,0,0,0
615490,2002,1999,0,0,2,49,0,12,10,27,...,229,0,6,0,7,0,7,0,65306,1
615491,1997,1994,0,1,0,5,-1,23,3,13,...,76,0,0,0,1,0,1,0,0,0
615492,2001,2000,1,11,4,41,11,29,36,90,...,220,15,525,0,2,0,2,2257,11437257,1
615493,1993,1992,3,6,4,21,18,11,7,14,...,104,6,51,0,0,0,0,137,20483,1
615494,2003,2002,0,3,10,73,32,60,22,66,...,153,11,547,0,1,0,1,859,3076213,1
615495,1998,2003,1,2,1,10,20,10,32,89,...,193,0,3,0,13,2,11,0,246972,0
615496,1996,1995,0,0,2,6,30,29,97,23,...,51,5,162,0,10,1,9,118,655462,1
615497,2000,1998,0,3,0,8,-1,-1,25,206,...,83,2,409,0,17,4,13,312,29992175,1
615498,1996,2003,0,0,0,0,10,4,2,16,...,91,0,0,0,2,0,2,0,0,0
615499,1993,1999,0,0,0,0,6,7,11,36,...,104,0,0,0,2,1,1,0,0,0
615500,1994,2001,0,0,0,3,31,60,35,23,...,159,0,1,0,11,1,10,0,31472,0
615501,1999,1997,0,0,0,2,41,0,34,7,...,95,0,0,0,8,0,8,0,0,0
615502,1998,1992,0,4,0,21,16,14,8,3,...,146,0,0,0,2,0,2,0,0,0
615503,2000,1999,0,2,0,27,42,56,12,64,...,99,7,191,0,6,1,5,866,4144014,1
615504,1998,2000,0,0,0,0,99,1,42,4,...,105,0,0,0,5,0,5,0,0,0
615505,2002,1997,0,0,0,11,26,30,21,31,...,91,0,0,0,1,0,1,0,0,0
615506,2003,2002,0,1,5,19,13,19,28,29,...,161,5,171,0,2,1,1,1561,15338945,1
615507,1997,1993,2,2,2,2,-1,43,7,51,...,110,5,66,0,1,0,1,142,66065,1
615508,1997,1992,0,0,0,6,7,49,6,5,...,150,0,0,0,4,0,4,0,0,0
615509,2000,1996,1,3,1,8,12,53,27,10,...,95,0,0,0,6,0,6,0,0,0
615510,2002,2001,0,0,0,0,53,-1,7,2,...,114,0,0,0,0,0,0,0,0,0
615511,1999,1998,0,2,1,31,53,-1,79,282,...,130,5,1209,0,52,26,26,5747,128915889,1

In [169]:
classic.columns

Index(['year1', 'year2', 'T1T2_c', 'T1Ab2_c', 'T2Ab1_c', 'Ab1Ab2_c',
       'aut1_sum', 'aut2_sum', 'connection1', 'connection2', 'len1', 'len2',
       'edge2', 'edge3', 'edge2_neg', 'edge3_neg', 'edge3_neg_middle',
       'edge3_neg_sid', 'edge2_weighted', 'edge3_weighted', 'rnn'],
      dtype='object')

In [185]:
features_test.columns

Index(['year1', 'year2', 'T1T2_c', 'T1Ab2_c', 'T2Ab1_c', 'Ab1Ab2_c',
       'aut1_sum', 'aut2_sum', 'connection1', 'connection2', 'len1', 'len2',
       'edge2', 'edge3', 'edge2_neg', 'edge3_neg', 'edge3_neg_middle',
       'edge3_neg_sid', 'edge2_weighted', 'edge3_weighted', 'rnn'],
      dtype='object')